// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel March

// DATA STRUCTURES
struct Triangle{
    float3 vertexA;
    float3 vertexB;
    float3 vertexC;
}

// INPUTS (From c# to GPU)
StructuredBuffer<float> SDFGrid;

// Dimensions of the SDF grid
uint3 GridSize;
float3 VoxelSize;
float isoLevel; // The "surface" level. For our SDF, water Surface is exactly at 0.0

// OUTPUTS (From GPU to c#)
AppendStructuredBuffer<Triangle> OutputTriangles; // note append becuase some threads might finish before other



[numthreads(8,8,8)]
void March (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= GridSize.x - 1 || id.y >= GridSize.y - 1 || id.z >= GridSize.z - 1) return; // out of bounds check
    
    // TODO: insert actual code here!

   
}
